INCLUDE_DIRECTORIES( ${QTBASICUTILS_INCLUDE_DIR} )
LINK_DIRECTORIES( ${QTBASICUTILS_LIB_DIR} )
ADD_DEFINITIONS(-DUSE_QTBASICUTILS)
set (UPMC_EXTERNAL_LIBS ${UPMC_EXTERNAL_LIBS} ${QTBASICUTILS_LIBRARY})