//
// C++ Interface: QCmdParseError
//
// Description: 
//
//
// Author:  <>, (C) 2009
//
// Copyright: See COPYING file that comes with this distribution
//
//

namespace QTUTILS {

class QCmdParseError 
{
public:
	static QString	GetErrorString(quint32 nErrorCode, QString str0=_T(""), QString str1=_T(""),
		QString str2=_T(""));
public:
	enum errorCode {STATUS_OK, NO_DEFAULT_COMMAND,PARAM_NOT_OPTION, PARAM_EXTRA_DATA, PARAM_MISSING_DATA, 
		PARAM_TOO_BIG, PARAM_TOO_SMALL, PARAM_INVALID_DATA, PARAM_ALLREADY_SET, OPTION_ALLREADY_ADDED, 
		OPTION_NOT_FOUND, OPTION_WRONG_TYPE,ARGUMENT_ALLREADY_ADDED, ARGUMENT_NOT_FOUND, 
		ARGUMENT_WRONG_TYPE, TOO_MANY_ARGUMENTS,NOT_ENOUGH_ARGUMENTS, COMMAND_ALLREADY_ADDED, 
		PARAM_NOT_COMMAND, COMMAND_NOT_SEPARATED, MEMORY_ALLOCATION_ERROR, MEMORY_CORRUPTION_ERROR, 
		FOLDER_MUST_EXIST, FILE_MUST_EXIST, FILE_MUST_NOT_EXIST, FILE_NOT_IN_CWD, MUST_BE_FILE,
		MUST_BE_FOLDER, NUM_ERRORS };
};

}; //namespace QTUTILS