<<<<<<< .mine
macro( setup_naming_convention Name )

=======
IF(MSVC)
>>>>>>> .r180
<<<<<<< .mine
if (NOT "${PROJECT_COMPILER_VERSION}" STREQUAL "")

	if (NOT "${${Name}_VERSION_STRING}" STREQUAL "")
		set(ARCH_SUFFIX)
		if (NOT "${PROJECT_ARCH}" STREQUAL "")
			set(ARCH_SUFFIX "-${PROJECT_ARCH}")
		endif (NOT "${PROJECT_ARCH}" STREQUAL "")
		SET(CMAKE_DEBUG_POSTFIX "-${${Name}_VERSION_STRING}-d-${PROJECT_COMPILER_VERSION}${ARCH_SUFFIX}")
		SET(CMAKE_RELEASE_POSTFIX "-${${Name}_VERSION_STRING}-r-${PROJECT_COMPILER_VERSION}${ARCH_SUFFIX}")
		SET(CMAKE_RELWITHDEBINFO_POSTFIX "-${${Name}_VERSION_STRING}-rd-${PROJECT_COMPILER_VERSION}${ARCH_SUFFIX}")
		SET(CMAKE_MINSIZEREL_POSTFIX "-${${Name}_VERSION_STRING}-rms-${PROJECT_COMPILER_VERSION}${ARCH_SUFFIX}")
	else(NOT "${${Name}_VERSION_STRING}" STREQUAL "")
		message( WARNING "${Name}_VERSION_STRING must be set before using the setup_naming_convention MACRO." )
	endif(NOT "${${Name}_VERSION_STRING}" STREQUAL "")
else(NOT "${PROJECT_COMPILER_VERSION}" STREQUAL "")
	message( WARNING "PROJECT_COMPILER_VERSION must be set before using the setup_naming_convention MACRO." )
endif (NOT "${PROJECT_COMPILER_VERSION}" STREQUAL "")

endmacro( setup_naming_convention )=======
    SET(CMAKE_CXX_FLAGS "/MP /WL /GR /EHa" ) 
    ADD_DEFINITIONS(-D_CRT_SECURE_NO_WARNINGS)
	
	IF(MSVC10)
		SET(CMAKE_DEBUG_POSTFIX "_d_2010")
		SET(CMAKE_RELEASE_POSTFIX "_2010")
		SET(CMAKE_RELWITHDEBINFO_POSTFIX "_2010")
	ENDIF(MSVC10)
	
	IF(MSVC90)
		SET(CMAKE_DEBUG_POSTFIX "_d_2008")
		SET(CMAKE_RELEASE_POSTFIX "_2008")
		SET(CMAKE_RELWITHDEBINFO_POSTFIX "_2008")
	ENDIF(MSVC90)
	
	IF(MSVC80)
		SET(CMAKE_DEBUG_POSTFIX "_d_2005")
		SET(CMAKE_RELEASE_POSTFIX "_2005")
		SET(CMAKE_RELWITHDEBINFO_POSTFIX "_2005")
	ENDIF(MSVC80)
	
	IF(MSVC71)
		SET(CMAKE_DEBUG_POSTFIX "_d_2003")
		SET(CMAKE_RELEASE_POSTFIX "_2003")
		SET(CMAKE_RELWITHDEBINFO_POSTFIX "_2003")
	ENDIF(MSVC71)
	
	IF(MSVC70)
		SET(CMAKE_DEBUG_POSTFIX "_d_2002")
		SET(CMAKE_RELEASE_POSTFIX "_2002")
		SET(CMAKE_RELWITHDEBINFO_POSTFIX "_2002")
	ENDIF(MSVC70)
	
	IF(MSVC60)
		SET(CMAKE_DEBUG_POSTFIX "_d_vc6")
		SET(CMAKE_RELEASE_POSTFIX "_vc6")
		SET(CMAKE_RELWITHDEBINFO_POSTFIX "_vc6")
	ENDIF(MSVC60)
	
	#Name 64bit libaraies differenly
	IF(CMAKE_SIZEOF_VOID_P MATCHES 8)
		SET(CMAKE_DEBUG_POSTFIX "${CMAKE_DEBUG_POSTFIX}_x64")
		SET(CMAKE_RELEASE_POSTFIX "${CMAKE_RELEASE_POSTFIX}_x64")
		SET(CMAKE_RELWITHDEBINFO_POSTFIX "${CMAKE_RELWITHDEBINFO_POSTFIX}_x64")
	ENDIF(CMAKE_SIZEOF_VOID_P MATCHES 8)
		
ELSE(MSVC)
	SET(CMAKE_DEBUG_POSTFIX "_d")
ENDIF(MSVC)>>>>>>> .r180
