set(libqxt_GIT_REF 989c25349b658fde11318821f2c9063045e47424)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO drescherjm/libqxt-cmake
    REF ${libqxt_GIT_REF} # or use a specific tag/commit
    SHA512 80c09e77517f9fe6866df64885cc47745bc9d8cfdfbc2f1cae6464cb732b2dba7332d8ca1e78e9841b310db248090f6cf73022536da0052a099a2a933bd54947 # Replace with the actual sha512 generated by vcpkg hash
)

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
)

vcpkg_cmake_build()
vcpkg_cmake_install()

# Fixup cmake config locations and paths. This is essential for vcpkg to setup the SimpleLibraryExampleConfig.cmake file 
# and setup each configuration for multiconfig generators like Visual Studio 2022. 
# Remember that vcpkg builds the Debug and Release config then maps the other configs: MinSizeRel, RelWithDebInfo to
# use the binaries created for the Release config. 
vcpkg_cmake_config_fixup(PACKAGE_NAME libQxt CONFIG_PATH lib/cmake/libQxt)
