set(libqxt_GIT_REF b82cbb1ea93726fb2809106e4618539f16f7308c)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO drescherjm/libqxt-cmake
    REF ${libqxt_GIT_REF} # or use a specific tag/commit
    SHA512 2b184d2c197d39148020b23f25589c07daf4ab0c7bb249468e4420ec46b7805f14b9af30d2bb6a97e165a1cf1d8fda3b9670b53d8777c8aeb0b5b8c4411dbca0 # Replace with the actual sha512 generated by vcpkg hash
)

vcpkg_cmake_configure(
    SOURCE_PATH ${SOURCE_PATH}
)

vcpkg_cmake_install()