set(libqxt_GIT_REF ac1386f173968ca744f28762e6bb480bb7af8945)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO drescherjm/libqxt-cmake
    REF ${libqxt_GIT_REF} # or use a specific tag/commit
    SHA512 5ecde5bcfc15b68f7faa0aaa48e26fdb1c59c2953193686bfe71a0370cbb9d0fe7c61e8cf9824dc79b8f53f9ef92609e2889e87e85ea5557c3433865c1487293 # Replace with the actual sha512 generated by vcpkg hash
)

vcpkg_cmake_configure(
    SOURCE_PATH ${SOURCE_PATH}
)

vcpkg_cmake_install()